title: AV-GYM
description: >-
  A modern fitness tracking and workout planning system

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal

# Theme settings
logo: /assets/img/logo.png
show_downloads: false
google_analytics: # Add your GA tracking ID here

# Site settings
baseurl: ""
url: ""

# Exclude from processing
exclude:
  - venv
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git
  - .github
  - README.md
  - LICENSE
  - "*.pyc"
  - __pycache__
  - .pytest_cache
