databases:
  - name: av-gym-db
    plan: free
    databaseName: avgymdatabase
    user: avgymuser

services:
  - type: web
    plan: free
    name: av-gym
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "cd fitcore && python -m gunicorn fitcore.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: av-gym-db
          property: connectionString
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_ALLOWED_HOSTS
        value: ".onrender.com"
      - key: DJANGO_SETTINGS_MODULE
        value: fitcore.settings_production
      - key: WEB_CONCURRENCY
        value: 4
