# Generated by Django 4.2.20 on 2025-04-10 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blogpage_options_remove_blogpage_categories_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpage',
            options={'ordering': ['-date'], 'verbose_name': 'Blog Post', 'verbose_name_plural': 'Blog Posts'},
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='blog_posts', to='blog.blogcategory'),
        ),
    ]
