# Generated by Django 4.2.20 on 2025-04-10 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blogpage_options_alter_blogpage_categories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpage',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='categories',
            field=models.ManyToManyField(blank=True, to='blog.blogcategory'),
        ),
    ]
